### ISSUE TITLE
Trouble using "/" at the end of a URI

### ISSUE THREAD

**Issue by ddeel** [DMTF/Redfish-Interface-Emulator#11]
Using a "/" at the end of a URI makes a difference with the emulator, depending upon whether it is for a leaf node (one at the edge of the tree) or a non-leaf node (one inside the tree).

For example, this is what happens when accessing a leaf node:

GET http://localhost:5000/redfish/v1/Systems/CS_5 results in a 200 OK response and produces reasonable output, but...

GET http://localhost:5000/redfish/v1/Systems/CS_5/ gets a 500 Internal Server Error response and the emulator console reports an exception originating in emulator.py.

However, this is what happens when accessing a non-leaf node:

GET http://localhost:5000/redfish/v1/Systems results in a 301 Moved Permanently response, and...

GET http://localhost:5000/redfish/v1/Systems/ results in a 200 OK response and produces reasonable output.

Note that the emulator behavior is different for getting a 200 OK response, depending upon whether the URI is for a leaf node or a non-leaf node.

This behavior is made more obvious by the Chrome Restlet Client extension. By default, Restlet does not automatically follow redirects, so if you leave the trailing "/" off for a non-leaf node, you'll get a 301 Moved Permanently response. Using the same URI with a trailing "/" (or telling Restlet to follow redirects) gets a 200 OK response. But having a trailing "/" on a leaf node causes an exception.

The Chrome Advance REST Client (ARC) seems to silently follow redirects, so there's no obvious difference between having or not having a trailing "/" on a URI for a non-leaf node. But having a trailing "/" on a leaf node still causes an exception.

Should the emulator be showing these differences between having and not having a trailing "/" on URIs?

**Comment by jcleung5549** [comment]
I think I see the problem.  I use Chrome Postman which also redirects silently.

How do you get to the Chrome Restlet Client?  I did a search and there seems to be several options. Can I use https://client.restlet.com/ or do I need to download something?

**Comment by ddeel** [comment]
I got the Chrome Restlet Client by going to the Chrome Web Store and searching for "Restlet". This link should also work: https://chrome.google.com/webstore/detail/restlet-client-rest-api-t/aejoelaoggembcahagimdiliamlcdmfm

**Comment by ddeel** [comment]
The problem described above was fixed by PR #12.
