### ISSUE TITLE
Service of static redfish tree GET response with ContentType: application/xml instead of ContentType: application/json

### ISSUE THREAD

**Issue by JohnMayfieldHPE** [DMTF/Redfish-Interface-Emulator#114]
Running a vanilla copy of v1.1.8 on a static redfish mockup starts the service and finds the redfish tree in the static directory OK, however when doing a GET on the service_root (or any other URI within the static tree) returns the content with the response header value ContentType set to application/xml instead of application/json.  This causes the client browser to attempt to parse the response as XML and returns errors to the user:  XML Parsing Error:  not well-formed

**Comment by jcleung5549** [comment]
Just tested the emulator using Postman and the response has Content-Type = application/json.  Will look further.

**Comment by jcleung5549** [comment]
When you make the GET request, is "Accept: application/json" set in the request header?

**Comment by JohnMayfieldHPE** [comment]
I was only using firefox for initiating the GET request, not postman.  I'm not sure how to tell Firefox to explicitly set Accept: application/json in the headers.

**Comment by jcleung5549** [comment]
A search finds...

Change FireFox's default Accept header to prefer JSON over XML

- In the address bar in FireFox, type “about:config”.
- Click the “I promise” button.
- In the search bar type “network. http. ...
- Double-click the setting.
- In the comma-separated list add a new value of “application/json” (without the quotes)

**Comment by JohnMayfieldHPE** [comment]
I think that is my problem, I didn't have the acceptable header content types in the request from firefox.  I'll adjust and most likely close this issue.  Thank you for the help John!
