### ISSUE TITLE
Describe the Infrastructure Generator in the README

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Interface-Emulator#17]
Need document on how to execute the infrastructure generator and the format of the input JSON (populate_config.json).

**Comment by joaomsoares** [comment]
Information on how to execute the infrastructure generator added. The format of the JSON was not included, but a pointer is made to the example "populate_config.json" which helps the user better understand the format of the input JSON. These updates are included in the pull request I just made.

**Comment by mraineri** [comment]
@jcleung5549 can this be closed out now?

**Comment by mraineri** [comment]
Closing; issue has been addressed
