### ISSUE TITLE
Populating should be optional

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Interface-Emulator#18]
The code in emulator.py seems to assume that ./infra_gen/populate_config.json exists.  The populate step should be options (come up empty if desired).  Options to do this are:
1. "POPULATE" Property is set to "emulator" in emulator_config.json
2. Existence of ./infra_gen/populate_config.json

```
    # Calls INFRAGEN and populates emulator according to populate-config.json
    with open(INFRAGEN_CONFIG, 'r') as f:
        infragen_config = json.load(f)
    populate(infragen_config.get('POPULATE',10))
```

**Comment by joaomsoares** [comment]
Done. Update included in the pull request I just made. 
In the emulator-config.json, if the variable POPULATE exists (should point to json file), it will try to run the generator, if not it will start empty.
Example of config file: 
{
  "SPEC": "Redfish",
  "MODE": "Local",
  "HTTPS": "Disable",
  "TRAYS": [],
  "POPULATE": "infragen/populate-config.json"
}

**Comment by mraineri** [comment]
@jcleung5549 can this be closed out now?

**Comment by mraineri** [comment]
Closing; issue has been addressed
