### ISSUE TITLE
Getting error “TypeError: ‘dict_values’ object does not support indexing”

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Interface-Emulator#24]
Attempts to access any of the systems under /redfish/v1/Systems result in the error.

Reason:
In Python 3, dict.values() (along with dict.keys() and dict.items()) returns a view, rather than a list. Therefor, one needs to wrap the call to dict.values() in a call to list. So: v = d.values() becomes v = list(d.values())

**Comment by mraineri** [comment]
Fixed in latest PR
