### ISSUE TITLE
Getting /redfish/v1/Systems results in "Internal System Error"

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Interface-Emulator#25]
(From Don Deel) Everything looks good at first. Using a browser (or the Restlet Client in Chrome) I can see the Redfish service root and access things like the Chassis and Managers collections. But no matter what I do, attempting to access Systems results in an “Internal Server Error” message. The emulator itself keeps running, the same way it would if I simply mis-typed something.

**Comment by jcleung5549** [comment]
(From Don Deel) Chrome’s URL cache was automatically placing a trailing “/” on both Systems and Chassis, no matter what I tried.  The fix was relatively easy: Go to /redfish/v1 in a browser window, open the Chrome developer tools window, and force an “Empty Cache and Hard Reload” using Chrome’s reload button.

**Comment by jcleung5549** [comment]
Should document behavior in the README (known issues)

**Comment by mraineri** [comment]
Fixed in latest PR
