### ISSUE TITLE
URL behaviors are different for static and dynamic resources

### ISSUE THREAD

**Issue by ddeel** [DMTF/Redfish-Interface-Emulator#30]
Using the Restlet Client, which does not do automatic redirection, the URLs that must be used for accessing static and dynamic emulator resources are different.

Dynamic resources must be accessed with URLs that do NOT end with a "/" character. If the URL for a dynamic resource ends with a "/" character, the emulator gives a "500 INTERNAL SERVER ERROR" response.

Static resources must be accessed with URLS that DO end with a "/" character. If the URL for a static resource does NOT end with a "/" character, the emulator gives a "301 MOVED PERMANENTLY" response, which is a redirect.

**Comment by mraineri** [comment]
Fixed by #36
