### ISSUE TITLE
Python dependency files need to be made consistent

### ISSUE THREAD

**Issue by ddeel** [DMTF/Redfish-Interface-Emulator#32]
There are four files that talk about Python dependencies, but they do not agree with each other:
(1) dependencies/Python Packages to place in directory.txt
(2) install.py
(3) installing_dependencies.txt
(4) requirements.txt

It would be good to have at least the requirements.txt file brought up-to-date with what is currently needed. Here is a list of packages that work for stand-alone operation on Windows (I'm not sure about the list of packages needed for other situations):
setuptools
markupsafe
itsdangerous
flask
aniso8601
pytz
flask_httpauth
requests
flask_restful
StringGenerator==0.2.1
urllib3

The version of StringGenerator is specified in this list because the latest version of StringGenerator (0.3.0) does not install on my Windows system.

If the other files that talk about Python dependencies are also still needed, they should be made to be consistent with an updated requirements.txt file.

**Comment by ddeel** [comment]
The latest version of StringGenerator (0.3.1) corrects the problem with installing it on Windows systems, so it is no longer necessary to force the version to be 0.2.1 for pip install.

The updated list of packages that work for stand-alone operation on Windows is now:
setuptools
markupsafe
itsdangerous
flask
aniso8601
pytz
flask_httpauth
requests
flask_restful
StringGenerator
urllib3

**Comment by jcleung5549** [comment]
There are many permutations of packages which would execute this emulator, which vary depending on whether  the emulator is run on Windows, Linux, or a cloud foundry.  The existence of the list of packages is for there user to correctly set up a working environment on which the execute the emulator.

So lists of packages seems more useful coming from the users/developers (bottom up) that from some prescriptive source (top-down).  This is especially true and the code and required packages evolves.

To that end, I would suggest a ./packageSet directory which hold environment that are known to work.  Each file would contain the output of "pip list".  The filename would contain the platform environment.

```
$ pip list
aniso8601 (1.2.1)
chardet (3.0.4)
Flask (0.12.2)
Flask-HTTPAuth (3.2.3)
Flask-RESTful (0.3.6)
itsdangerous (0.24)
Jinja2 (2.9.6)
MarkupSafe (1.0)
python-dateutil (2.6.1)
pytz (2017.2)
requests (2.18.4)
setuptools (20.10.1)
six (1.10.0)
StringGenerator (0.2.0)
urllib3 (1.22)
Werkzeug (0.12.2)
```

**Comment by ddeel** [comment]
That would work if we need to keep separate lists for different environments, but I think we could also simply place the output of "pip freeze" into requirements.txt, which could then be easily used in most environments by entering the command "pip install -r requirements.txt".

**Comment by mraineri** [comment]
PR merged
