### ISSUE TITLE
PATCH is not working properly

### ISSUE THREAD

**Issue by ddeel** [DMTF/Redfish-Interface-Emulator#35]
PATCH on Chassis returns 500 Internal Server Error.

**Comment by ddeel** [comment]
This is the message showing on the console after a PATCH on a Chassis member is attempted:
![image](https://user-images.githubusercontent.com/16329575/40243904-4789063c-5a76-11e8-8391-fa35631409b3.png)

**Comment by mraineri** [comment]
Closing; fixed in latest PR (with the stipulation that PCIe Switch PATCHing is not supported yet)
