### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Flask-RESTful-0.3.1.zip'

### ISSUE THREAD

**Issue by elham1296** [DMTF/Redfish-Interface-Emulator#41]
I got the following error when I run install.py
FileNotFoundError: [Errno 2] No such file or directory: 'Flask-RESTful-0.3.1.zip'

------------
I installed Flask-RESTful-0.3.1 using pip, which gives the following error;
No matching distribution found for Flask-RESTful-0.3.1

if I use "pip install -r requirements.txt" command, it adds the following directory:
/usr/lib64/python3.6/site-packages/flask_restful
its version is 3.6.
and it does not contain any zip file.

I also checked:
https://github.com/flask-restful/flask-restful
It does not contain version 0.3.1

**Comment by jcleung5549** [comment]
The install.py needs to be removed.  It's premised on carrying around zip files of Python packages doesn't work well.  Also the various environments that the emulator can run makes this problematic.  With issue #13, the best it to document the various python package sets where this emulator has been run.

**Comment by mraineri** [comment]
PR merged
