### ISSUE TITLE
Singleton POST command fails to add new resource instances created from templates

### ISSUE THREAD

**Issue by ddeel** [DMTF/Redfish-Interface-Emulator#43]
Many of the dynamic resources in the emulator are supposed to support emulator-only singleton POST commands that create new resource instances from pre-defined templates. These POST commands currently fail, due to a conflict with the way Infragen was added to the emulator.

Infragen uses the emulator’s internal method calls in dynamic resources instead of the Redfish API, and by itself this might have been OK, but in many cases the merged Infragen code made changes to the methods themselves in dynamic resources. These changes are causing failures for the POST commands that are supposed to create new instances from pre-defined templates.

There is no easy way to fix this problem. If the singleton POST commands are fixed to work as originally intended, Infragen will break. If the emulator is left the way it is, the ability to add new instances from pre-defined templates will remain broken. A reasonable solution would be to fix the emulator to work as originally intended, and to revise Infragen to work via the Redfish API instead of using the emulator’s internal method calls.

**Comment by jcleung5549** [comment]
I would lean toward breaking infragen and wait for it to get fixed.  The tool chain, for generating the python code files for the dynamic resource, is of higher priority.  When you break infragen, go file an issue (and the proposed solution).

**Comment by ddeel** [comment]
I've found a way to allow the emulator-only singleton POST commands to work as originally intended, and the fix does not break Infragen. I'll submit an appropriate pull request today.

**Comment by jautor** [comment]
Fixed and closed.
