### ISSUE TITLE
Collection POST command fails to add a resource instance to the ComputerSystem collection

### ISSUE THREAD

**Issue by ddeel** [DMTF/Redfish-Interface-Emulator#44]
A POST command to add a new instance to the ComputerSystem collection fails with an error message that says “KeyError: ‘Links’”. This happens no matter what is in the body of the POST command.

After reviewing the pull request history (see #16 ), this appears to be a consequence of the way support for composed systems was added to the ComputerSystem dynamic resource. Perhaps that work was not completed?

**Comment by ddeel** [comment]
I've found a way to resolve this Issue, and an appropriate pull request will be submitted today.

**Comment by jautor** [comment]
Fixed and merged.
