### ISSUE TITLE
Collection POST commands fail to add new resource instances to non-ComputerSystem resource/subresource collections

### ISSUE THREAD

**Issue by ddeel** [DMTF/Redfish-Interface-Emulator#45]
It should be possible to add new resources to many Redfish collections by doing a POST command to the collection. This currently works for the emulator's Chassis dynamic resource, but it fails for the rest of the emulator’s current set of dynamic resources.

Note: A similar problem with the ComputerSystem collection was reported separately (see #44 ), where the problems seem to be strongly tied to the way Infragen was implemented. The problem being reported here is for the other (non-ComputerSystem) dynamic resources, since it looks like they can be fixed without impacting the way Infragen currently works.

**Comment by mraineri** [comment]
PR merged
