### ISSUE TITLE
How to install intel cloud foundry in ubuntu 

### ISSUE THREAD

**Issue by chandra0293** [DMTF/Redfish-Interface-Emulator#65]
How to install intel cloud foundry in ubuntu

**Comment by jcleung5549** [comment]
The Intel cloud foundry is a service internal to Intel.  My understanding is that it is a replica of the public (cloudfoundry.org).  Information on publicly available foundries and local installation are available on that site. (I have not performed a "cf push" to a public foundry).

**Comment by jcleung5549** [comment]
Closing.  If response was not sufficient, please reopen and provide a comment.
