### ISSUE TITLE
how to read data from data centre to redfish spec ? 

### ISSUE THREAD

**Issue by chandra0293** [DMTF/Redfish-Interface-Emulator#70]
redfish emulator data is hard coded.i want read actual system chassis details  and sensor details how to get actual information from system (can we use IPC communication to get data from other software ?)

**Comment by mraineri** [comment]
Yes, the intent of the emulator is to contain canned data for testing purposes. It's possible to modify the tool to make calls into your system to get actual data, but that's really outside of the scope of an emulator. It seems like you're asking for an actual implementation of a Redfish service.

**Comment by jcleung5549** [comment]
The emulator can expose the model as dynamic by coding dynamic behavior into a resource property value.  The python strgen() and random functions calls are useful for coding this behavior.

If you are attempting to use the emulator as an implementation, you are in unknown territory.

**Comment by chandra0293** [comment]
> Yes, the intent of the emulator is to contain canned data for testing purposes. It's possible to modify the tool to make calls into your system to get actual data, but that's really outside of the scope of an emulator. It seems like you're asking for an actual implementation of a Redfish service.

yes i looking for actual implementation based our data model . how to start actual implementation ?

**Comment by chandra0293** [comment]
> The emulator can expose the model as dynamic by coding dynamic behavior into a resource property value. The python strgen() and random functions calls are useful for coding this behavior.
> 
> If you are attempting to use the emulator as an implementation, you are in unknown territory.

**Comment by jautor** [comment]
A quick search for "Building a REST service" will give you a ton of ideas for quickly implementing an HTTP service that can serve up JSON payload responses.  Once you have a basic REST service functional, it's just a matter of populating your resources with live data using the Redfish property definitions from the schema files.

**Comment by jcleung5549** [comment]
As python implementations, the Redfish simulators/emulators employed some of the packages referenced in guidance on building a RESTful service.  The code shows you how these packages can work together to simplify your development effort.
- The Redfish-Mockup-Server uses the request/grequest packages
- The Redfish-Profile-Simulator uses the flask package
- The Redfish-Interface-Emulator uses the flask, flask_restful and flask_httpauth packages

**Comment by chandra0293** [comment]
thank you so much .

**Comment by chandra0293** [comment]
is there any difference between Redfish-Profile-Simulator and
Redfish-Interface-Emulator ?

**Comment by jautor** [comment]
The Profile simulator is a fairly static model showing an implementation of the proposed OCP profile (from a while ago) - this Emulator is much more full-featured and extensible.

**Comment by jcleung5549** [comment]
SNIA (snia.org) extended Redfish to manage networked storage and storage services.  They also created the Swordfish API Emulator (github.com/SNIA/Swordfish-API-Emulator). Their repository contains the incremental files in order to emulator Swordfish objects.  On their repository, traverse the path ./api_emulator/redfish to see the resource emulation code.

**Comment by mraineri** [comment]
@chandra0293 does that answer your questions? Can we close this issue?

**Comment by mraineri** [comment]
Closing
