### ISSUE TITLE
unittests.py was broken

### ISSUE THREAD

**Issue by felipeportella** [DMTF/Redfish-Interface-Emulator#73]
The file unittests.py has two minor Python syntax issues raised if we try to run it:

1)   File "unittests.py", line 62
    logger.info('PASS: GET of {0} successful (response below)\n {1}'.format(getting, r.text))
                                                                                            ^
TabError: inconsistent use of tabs and spaces in indentation

2)    File "unittests.py", line 156
    print'Testing interface at:', sys.argv[2]
                               ^
SyntaxError: invalid syntax

**Comment by mraineri** [comment]
Closing; PR merged
