### ISSUE TITLE
account_sevice.py should be renamed

### ISSUE THREAD

**Issue by alansill** [DMTF/Redfish-Interface-Emulator#8]
account_sevice.py should be renamed account_service.py

Internal contents are correct, so this is just a naming issue.

**Comment by billdodd** [comment]
Agreed.

And note that the related import statement in emulator_ssl.py needs to be updated when the fix is made:

```
from api_emulator.account_sevice import AccountService
```

**Comment by billdodd** [comment]
Fixed in https://github.com/DMTF/Redfish-Interface-Emulator/pull/10
