### ISSUE TITLE
Redfish interface emulator is a standard API designed or standard data-model designed 

### ISSUE THREAD

**Issue by chandra0293** [DMTF/Redfish-Interface-Emulator#80]
Redfish interface emulator is a standard API designed or standard data-model designed

**Comment by jcleung5549** [comment]
If this is a question, please elaborate.

**Comment by chandra0293** [comment]
For example rest api http://localhost:5000/redfish/v1/
                                  http://localhost:5000/redfish/v1/MDCChassis
                                  http://localhost:5000/redfish/v1/Status
                                  http://localhost:5000/redfish/v1/Settings
these are not standard api in redfish

**Comment by jcleung5549** [comment]
Are you using the Emulator is static or dynamic mode?  In both cases, you control what resources appear in the hierarchy.  So you control how compliant the Emulator is to the Redfish standard.
