### ISSUE TITLE
how to get data to redfish service from system ?

### ISSUE THREAD

**Issue by chandra0293** [DMTF/Redfish-Interface-Emulator#83]
redfish service get data from redfish host , redfish host is like any third-party(like inter process communication ,database ) software or need to use any specific commands.

**Comment by jcleung5549** [comment]
The work "get to" and "from" in the same sentence makes it hard to understand.

- The Redfish Service runs on a system being managed.
- A Redfish client sends data to Redfish Service via a HTTP PATCH or POST
- A Redfish clients obtains data from a managed system, but issuing a HTTP GET to the Redfish Service.

**Comment by chandra0293** [comment]
thank you .
