### ISSUE TITLE
sample redfish emulator implementing .is it correct?

### ISSUE THREAD

**Issue by chandra0293** [DMTF/Redfish-Interface-Emulator#84]
from flask import Flask
from flask_restful import Resource, Api
import sys, traceback
import copy
import strgen
from utils import replace_recurse

from Acclipc.mdc_webtask import *

BASE_PATH = "/redfish/v1/"

app = Flask(__name__)
api = Api(app)

class ResourceCollection(Resource):
	def __init__(self):
		self.rest_base = BASE_PATH
		self.uuid = ""

	def get(self):
		"""
		Configuration property - Service Root
		"""
		config = {
			'@odata.context': self.rest_base + '$metadata#ServiceRoot',
			'@odata.type': '#ServiceRoot.1.0.0.ServiceRoot',
			'@odata.id': self.rest_base,
			'Id': 'RootService',
			'Name': 'Root Service',
			'ServiceVersion': '1.0.0',
			'UUID': self.uuid,
			'Links': {
				'Chassis': {'@odata.id': self.rest_base + 'Chassis'}
			}
		}

		return config

class Chassis(Resource):
	
	def __init__(self):
		self.rb = BASE_PATH
		self.config = {
			'@odata.context': self.rb + '$metadata#ChassisCollection.ChassisCollection',
			'@odata.id': self.rb + 'Chassis',
			'@odata.type': '#ChassisCollection.1.0.0.ChassisCollection',
			'Name': 'Chassis Collection',
			'Member@odata.count': 1,
			'Member' : self.rb + 'Chassis/Chassis-1',
			}	
			
	def get(self):
		try:
			resp = self.config, 200
		except Exception:
			traceback.print_exc()
			resp = INTERNAL_ERROR
		return resp
class Chassisinfo(Resource):
	
	def __init__(self):
		self.rb = BASE_PATH
		self.config = {
			"@odata.context": self.rb +"$metadata#Chassis.Chassis",
			"@odata.id": self.rb + "Chassis",
			"@odata.type": "#Chassis.v1_0_0.Chassis",
			'Name': 'MDC System Chassis',
			"ChassisType": "RackMount",
			"SerialNumber": "",
			"PartNumber": "",
			"MaxPower": "",
			"Chassis ID": "",
			"AssetTag": "",
			"Oem": {
				"Links": {
					"Cartridge": [ 
						{
							"@odata.id": self.rb +"Chassis/Chassis-1/Cartridge"
						}
					],
					"Switch": [ 
						{
							"@odata.id": self.rb +"Chassis/Chassis-1/Switch"
						}
					]
				}
			}
			}
			
	def get(self,ident):
		global wildcards
		res = login("accl","accl")
		result = chassisinfo()
		self.config['@odata.id']= self.rb + ident
		self.config['PartNumber']= result[0]
		self.config['SerialNumber']= result[1]
		self.config['MaxPower']= result[2]
		self.config['Chassis ID']= result[3]
		self.config['AssetTag']= result[4]
		return self.config, 200
		
class CartridgeCollection(Resource):
	
	def __init__(self):
		self.rb = BASE_PATH
		self.cartridge = "Cartridge"
		self.switch = "Switch"
		self.config = {
			'@odata.context': self.rb + '$metadata#cartridgeCollection.cartridgeCollection',
			'@odata.id': self.rb + 'Cartridge',
			'@odata.type': '#cartridgeCollection.1.0.0.cartridgeCollection',
			'Name': 'Cartridge Collection',
			'Links': {}
		}
		self.config['Links']['Member@odata.count'] = ''
		self.config['Links']['Members'] = ''
		
	def get(self,ident1,ident2):
		if ident2 == self.cartridge:
			self.config['Name']=self.cartridge + " Collection"
			self.config['Links']['Member@odata.count'] = 12
			self.config['Links']['Members'] = ''
			return self.config, 200
		elif ident2 == self.switch:
			self.config['Name']=self.switch + " Collection"
			self.config['Links']['Member@odata.count'] = 2
			self.config['Links']['Members'] = ''
			return self.config, 200
api.add_resource(ResourceCollection, '/redfish/v1')
api.add_resource(Chassis, '/redfish/v1/Chassis')
api.add_resource(Chassisinfo, '/redfish/v1/Chassis/<string:ident>')
api.add_resource(CartridgeCollection, '/redfish/v1/Chassis/<string:ident1>/<string:ident2>')

if __name__ == '__main__':
    app.run('0.0.0.0', debug=True)

**Comment by jcleung5549** [comment]
You should follow the instructions in the README section "Dynamic Emulation".
1. Create an API file (resource_api.py) file
2. Create a template file (resource.py)
3. If replacing a resource subordinate to the ServiceRoot, edit resource_emulator.py

To make things easier, the following examples exist in the repository
- Examples of API files: ./api_emulator/redfish/eg_resource_api.py and eg_subresource_api.py
- Examples of template files: ./api_emulator/redfish/templates/eg_resource.py and eg_subresource.py

**Comment by jcleung5549** [comment]
The code fragment you include has calls the Flask(), app.run and api.add_resource. These fragments are in the emulator_api.py file.  You shouldn't need to touch this or extract any code from it.

**Comment by chandra0293** [comment]
thank you

**Comment by chandra0293** [comment]
*in this file populate-config.json chassis count 13 can i change this count
to 1. *

*chassis contain 12 cartridges(here cartridges are Server,storage ,NIC
,FPGA,GPU) or 24 cartridge, 2 switch card *

*each cartridge(server ) have 2 nodes *
* each switch having 2 devices (Device are NIC ,Storage ,FPGA,GPU ) *

**Comment by chandra0293** [comment]
how to change this populate-config.json file based on my requirements?
Chassis Count -1
Cartridge Count -12 or 24 (Server , storage,NIC,FPGA ,GPU)
Each Cartridge node count -2 or 4 (if cartridge is server)
SwitchCard count -2
Each SwitchCard Device count -2 (Storage ,NIC ,FPGA,GPU)

**Comment by jcleung5549** [comment]
Before using Infragen, have you verified that you can manual create the dynamic resources?  This can be done by doing a HTTP POST to the new resource instances.  You should be able to manually POST each resource to verify each dynamic resource is operational.  

(BTW, I did not write the Infragen code.  It was contributed to the repository by another developer. So I will not be of much help in crafting an emulator-config.json file for your purposes.)

**Comment by chandra0293** [comment]
yes manually created dynamic resources its working thank you.
