### ISSUE TITLE
Request to create a Python module for this tool

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Interface-Emulator#9]
Currently, SNIA is extending code base to become the Swordfish Interface Emulator.  The instructions for putting the packages together is getting complex.  It would be simpler if ‘pip redfish-emul’ could be run, followed by ‘pip swordfish-emul’.

**Comment by mraineri** [comment]
Adding @jcleung5549 to work with others on how to restructure the repo (and not break the tool) so it can be easily submitted.

**Comment by mraineri** [comment]
@jcleung5549 do we still need this? Is SNIA going to be releasing their own copy and thus we don't need to release this via pip?

**Comment by jcleung5549** [comment]
This can be closed.  My latest thought is that the Swordfish Interface Emulator should just fork from this repository, then it perform an installation in one step, as oppose to install this emulator, then layering the Swordfish files.
