### ISSUE TITLE
Incorrect "dummy" values in static mockup for processors

### ISSUE THREAD

**Issue by rbrunner2** [DMTF/Redfish-Interface-Emulator#92]
I was looking at the contents of /redfish/v1/Systems/System-*/Processors/CPU* in the static mockup. I think it would be helpful if the CPU data matched real processors. For example,  /redfish/v1/Systems/System-7/Processors/CPU0 shows this:

"Manufacturer": "Intel(R) Corporation",
    "Model": "Multi-Core Intel(R) Xeon(R) processor 7500 Series",
    "ProcessorId": {
        "VendorId": "GenuineIntel",
        "IdentificationRegisters": "0x34AC34DC8901274A",
        "EffectiveFamily": "0x42",         <<< should be “0x6”
        "EffectiveModel": "0x61",         <<< should be “0x2E”
        "Step": "0x1",                            <<< should be “0x6”
        "MicrocodeInfo": "0x429943"   <<< should be “0x0000000B” or higher

If permissible by this team, I'd be happy to make a patch with the correct values. Please let me know. Thanks!

**Comment by jautor** [comment]
Absolutely!  Please bring that to the Redfish Forum as those mockups are published as part of DSP2043.  Then we can publish an updated set of mockups that include more realistic data.

**Comment by rbrunner2** [comment]
OK, will do. Thanks!
