### ISSUE TITLE
Issues with Using Created Mockup to use Static Emulator

### ISSUE THREAD

**Issue by seancmasters** [DMTF/Redfish-Interface-Emulator#93]
I created my own mockup with a live redfish service from the Redfish-Mockup-Creator and Redfish-Mockup-Server runs as expected. However, when I follow the instructions to use my own mockup with the Redfish-Interface-Emulator it doesn't see my mockup that I'm trying to use. Replacing the \api_emulator\redfish\static directory with my mockup doesn't work. The readme and instructions found in /doc seem to be a little inconsistent, and I'm trying to find out what I'm doing wrong.

**Comment by jcleung5549** [comment]
Before you copied in your mockup, did you launch the emulator with the default mockup to make sure that worked?

**Comment by seancmasters** [comment]
The sample/default mockup doesn't work either

**Comment by jcleung5549** [comment]
That doesn't happen :-).  The most efficient way to resolve is a quick video-meeting.

**Comment by seancmasters** [comment]
That would be great. My email address is sean.masters@hpe.com

**Comment by mraineri** [comment]
Closed; PR merged that addresses this
